CSVReaderNet/Models/ErrorViewModel.cs
namespace CSVReaderNet.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CSVReaderNet/Models/Resum.cs
using CsvHelper.Configuration.Attributes;

namespace CSVReaderNet.Models
{
    public class Resum
    {
        [Index(0)]
        public string Name { get; set; }
        [Index(1)]
        public DateOnly Date { get; set; }
        [Index(2)]
        public bool Maried { get; set; }
        [Index(3)]
        public string Phone { get; set; }
        [Index(4)]
        public decimal Salary { get; set; }
    }
}

CSVReaderNet/Controllers/HomeController.cs
using CSVReaderNet.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CSVReaderNet.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CSVReaderNet/Controllers/ResumeController.cs
using CsvHelper;
using CSVReaderNet.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Globalization;
using IHostingEnvironment = Microsoft.AspNetCore.Hosting.IHostingEnvironment;

namespace CSVReaderNet.Controllers
{
    public class ResumeController : Controller
    {
        [HttpGet]
        public IActionResult Index(List<Resum> resume = null)
        {
            resume = resume == null ? new List<Resum>() : resume;
            return View(resume);
        }

        [HttpPost]
        public IActionResult Index(IFormFile file, [FromServices] IHostingEnvironment hostingEnvironment)
        {
            #region Upload CSV
            string fileName = $"{hostingEnvironment.WebRootPath}\\files\\{file.FileName}";
            using (FileStream fileStream = System.IO.File.Create(fileName))
            {
                file.CopyTo(fileStream);
                fileStream.Flush();
            }
            #endregion

            var resume = this.GetResumList(file.FileName);
            return Index(resume);
        }

        private List<Resum> GetResumList(string fileName)
        {
            List<Resum> resume = new List<Resum>();

            #region Read CSV
            var path = $"{Directory.GetCurrentDirectory()}{@"\wwwroot\files"}" + "\\" + fileName;
            using (var reader = new StreamReader(path))
            using (var csv = new CsvReader(reader, CultureInfo.InvariantCulture))
            {
                csv.Read();
                csv.ReadHeader();
                while (csv.Read())
                {
                    var resum = csv.GetRecord<Resum>();
                    resume.Add(resum);
                }
            }
            #endregion

            #region Create CSV
            
            path = $"{Directory.GetCurrentDirectory()}{@"\wwwroot\files"}";
            using (var write = new StreamWriter(path + "\\NewFile.csv"))
                using (var csv = new CsvWriter(write, CultureInfo.InvariantCulture))
                    { csv.WriteRecords(resume); }

            #endregion

            return resume;
        }
    }
}

CSVReaderNet/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CSVReaderNet/Views/Resume/Index.cshtml
@model IEnumerable<Resum>
@{
    Layout = null;
}

<form asp-controller="Resume" asp-action="Index" method="post" enctype="multipart/form-data">
<input type="file" name="file" />
<hr />
<button type="submit">Upload</button>
</form>

@if (Model.Count() > 0)
{
    <hr />
    <table cellpadding="0" cellspacing="0" border="1">
        <tr>
            <td>Name</td>
            <td>Date</td>
            <td>Maried</td>
            <td>Phone</td>
            <td>Salary</td>
        </tr>
        @foreach (Resum resume in Model)
        {
        <tr>
                    <td>@resume.Name</td>
                    <td>@resume.Date</td>
                    <td>@resume.Maried</td>
                    <td>@resume.Phone</td>
                    <td>@resume.Salary</td>
        </tr>
        }
    </table>
}

CSVReaderNet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CSVReaderNet</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CSVReaderNet.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CSVReaderNet</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CSVReaderNet - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>